var express = require('express')
var app = express()
var bodyParser = require('body-parser')
var mongoose = require('mongoose')
mongoose.connect('mongodb+srv://oppo:oppo@learn-mongo-db-xcn8m.mongodb.net/test?retryWrites=true&w=majority')
app.use(bodyParser.json())
app.get('/', function (req, res) {
    res.send('succefully connected to server')
    console.log('succefully connected to server')
})

app.use('/employees',require('./app/routes/employees'))
app.use('/products',require('./app/routes/products'))
app.use('/users',require('./app/routes/users'))
app.listen(8080)